#pragma config(Motor,  port2,           rightMotor,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           leftMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           rightTopArm,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           leftTopArm,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           rightLowArm,   tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           leftLowArm,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           Intake,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           claw,          tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

while(1==1){
    motor[leftMotor]  = (vexRT[Ch2] + vexRT[Ch1])/2;  // (y + x)/2
    motor[rightMotor] = (vexRT[Ch2] - vexRT[Ch1])/2;

  if(vexRT[Btn7L]==1){
  motor[Intake]= -63;
  }
  else if(vexRT[Btn7D]==1){
  motor[Intake]= 63;
  }
  else{motor[Intake]=0;}

  if(vexRT[Btn5D]==1){
  motor[rightTopArm]=-21;
  motor[leftTopArm]=-21;
  }
  else if(vexRT[Btn5U]==1){
  	 motor[rightTopArm]=50;
     motor[leftTopArm]=50;
  }
  else{
  	motor[rightTopArm]=0;
    motor[leftTopArm]=0;
      }

      if(vexRT[Btn6D]==1){
  motor[rightLowArm]=-21;
  motor[leftLowArm]=-21;
  }
  else if(vexRT[Btn6U]==1){
  	 motor[rightLowArm]=63;
     motor[leftLowArm]=63;
  }
  else{
  	motor[rightLowArm]=0;
    motor[leftLowArm]=0;
      }

  if(vexRT[Btn8R]==1){
    	motor[claw]=42;
  }
  if(vexRT[Btn8D]==1){
  	  motor[claw]=-42;
  }
  else
  	{motor[claw]=0;}


}

}
